name: dockertest
on:
  branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: build docker image
      run: docker build -t studentportal .
    - name: list docker images
      run: docker images
    - name: run container 
      run: docker run - name container1 studentportal
    - name: list running containers
      run: docker ps 