name: dockertest
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t studentportal .
      - name: list docker images
        run: docker images
      - name: run container 
        run: docker run -d --name container1 -p 5000:5000 studentportal
      - name: list running containers
        run: docker ps 
      - name: build deploy file
        run: echo "hi welcome to my docker lab" > deploy.txt  
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-report
          path: deploy.txt
  Build:
    needs: deploy 
    runs-on: ubuntu-latest
    steps:
      - name: print msg
        run: echo "hello"
      - name: download artifact
        uses: actions/download-artifact@v4
        with:   
          name: deploy-report
      - name: display download content
        run: cat deploy.txt